name: Docker Build

on:
  workflow_run:
    workflows: ["Run Snyk Analysis"]
    types:
      - completed


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug Docker Login
        run: |
          echo "Checking Docker login status..."
          docker info || echo "Docker is not logged in or there was an error."

       - name: Configure Docker to use Google Artifact Registry
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: docker.io/elenagaz/note-api:latest  
