name: Docker Build

on:
  workflow_run:
    workflows: ["Test and Snyk Analysis"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.EX2_PAT }} 

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/docker-image:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/docker-image:latest
